# ==============================================================================
# File: token.py
# Project: RCL (Robot Command Language) Compiler
# Purpose: Define all token types and the Token data structure.
# ==============================================================================

class TokenType:
    """
    TokenType defines the categorical classifications (names) for all valid
    lexical units in the Robot Command Language (RCL).
    """

    # 1. Program Structure Keywords
    START = "START"          # Marks the beginning of an RCL program
    END = "END"              # Marks the end of an RCL program

    # 2. Movement & Motion Keywords
    MOVE = "MOVE"            # Command to move the robot
    FORWARD = "FORWARD"      # Direction parameter for MOVE
    BACKWARD = "BACKWARD"    # Direction parameter for MOVE

    # 3. Turning & Orientation Keywords
    TURN = "TURN"            # Command to rotate the robot
    LEFT = "LEFT"            # Rotation direction for TURN
    RIGHT = "RIGHT"          # Rotation direction for TURN

    # 4. Robot Action Keywords
    PICK = "PICK"            # Command to pick up an object
    DROP = "DROP"            # Command to drop an object
    WAIT = "WAIT"            # Command to pause robot execution

    # 5. Literals
    NUMBER = "NUMBER"        # Integer values (e.g., 10, 5, 100)

    # 6. Special & Delimiter Tokens
    NEWLINE = "NEWLINE"      # End of line character ('\n')
    EOF = "EOF"              # End Of File / End of input stream
    INVALID = "INVALID"      # Unrecognized character or keyword


class Token:
    """
    Represents an individual token generated by the Lexical Analyzer.
    
    Attributes:
        type (str): The classification of the token from TokenType (e.g., TokenType.MOVE).
        value (str): The actual lexeme (raw text) extracted from the source code.
        line (int): The 1-based line number where the token was found.
        column (int): The 1-based column number where the token starts.
    """

    def __init__(self, token_type: str, value: str, line: int, column: int):
        self.type = token_type
        self.value = value
        self.line = line
        self.column = column

    def __str__(self):
        # Human-readable representation for displaying output
        if self.type == TokenType.NUMBER:
            return f"NUMBER({self.value})"
        elif self.type == TokenType.NEWLINE:
            return "NEWLINE"
        elif self.type == TokenType.EOF:
            return "EOF"
        elif self.type == TokenType.INVALID:
            return f"INVALID('{self.value}') at Line {self.line}, Col {self.column}"
        return f"{self.type}"

    def __repr__(self):
        # Detailed representation showing all metadata
        return f"Token(type={self.type}, value='{self.value}', line={self.line}, col={self.column})"


# ==============================================================================
# Self-Test block for Step 1
# ==============================================================================
if __name__ == "__main__":
    print("==================================================")
    print("      Testing Step 1: token.py (RCL Tokens)       ")
    print("==================================================")

    # Create sample tokens
    t1 = Token(TokenType.START, "START", line=1, column=1)
    t2 = Token(TokenType.MOVE, "MOVE", line=2, column=1)
    t3 = Token(TokenType.FORWARD, "FORWARD", line=2, column=6)
    t4 = Token(TokenType.NUMBER, "10", line=2, column=14)
    t5 = Token(TokenType.NEWLINE, "\n", line=2, column=16)
    t6 = Token(TokenType.INVALID, "@", line=3, column=5)
    t7 = Token(TokenType.EOF, "", line=4, column=1)

    sample_tokens = [t1, t2, t3, t4, t5, t6, t7]

    print("\n1. Displaying __str__() format (used in readable output):")
    for t in sample_tokens:
        print(f"  - {str(t)}")

    print("\n2. Displaying __repr__() format (showing metadata):")
    for t in sample_tokens:
        print(f"  - {repr(t)}")

    print("\n[✓] Token module created and verified successfully!")